[package]
name = "encription"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

aes-gcm="0.9"
block-padding = "0.3.2"
generic-array = "0.14.5"
